### PR TITLE
Fuzzing: Add fuzzers for CertificateEntry and Serialization classes

### PR DESCRIPTION
**Pull request by arthurscchan**
#### Summary

Adding two new fuzzers focusing on CertificateEntry and Serialization classes.

### CODE REVIEW

**Comment by loosebazooka** [comment]
@arthurscchan I think we need to refactor these changes into the fuzzing gradle module

**Comment by arthurscchan** [comment]
Refactored.

**Comment by arthurscchan** [comment]
Refactored and fixed the formatting.

**Comment by loosebazooka** [comment]
same as #380 : I can commit these fuzzers with the CI fuzz issues if we want to deal with them in another PR?

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
