### PR TITLE
Add github actions oidc client

### PR DESCRIPTION
**Pull request by loosebazooka**
Signed-off-by: Appu Goundan <appu@google.com>

I don't think will work yet, might need to make the oidc token available in test

### CODE REVIEW

**Comment by patflynn** [comment]
You mean it won't work locally?

**Comment by loosebazooka** [comment]
> You mean it won't work locally?
yes and also not in CI cause I'm not sure what I'm doing, this needs to be a draft.

**Comment by loosebazooka** [comment]
I did it, I'm a genius

**Review by patflynn — APPROVED** [review]
nicely done.

**Pull request merged**
