### PR TITLE
Create CHANGELOG.md

### PR DESCRIPTION
**Pull request by loosebazooka**
Signed-off-by: Appu <appu@google.com>

### CODE REVIEW

**Review by vlsi — APPROVED** [review]
I'm ok with this, however, I think release-drafter GitHub action + GitHub releases would be easier to maintain.

**Comment by szpak** [comment]
> All versions prior to 1.0.0 are untracked

In fact, I believe that **important** changes should be documented, even in the releases prior to 1.0.0. Otherwise, the early adopters could be surprised by some big and non-backward compatible changes. Of course that can happen before 1.0.0, but in a good style is to notify about it.

**Comment by szpak** [comment]
> I'm ok with this, however, I think release-drafter GitHub action + GitHub releases would be easier to maintain.

@vlsi Do you think about some "GitHub action" to generate the release notes based on the PRs with a specific labels (e.g. "major")?

**Comment by loosebazooka** [comment]
github has some shortcuts to fill in the release notes into a release (since the last release or something).

**Comment by vlsi** [comment]
See https://github.com/release-drafter/release-drafter

What it does it updates "draft release notes on GitHub" every time a PR is merged or updated.

It enables to customize release sections based on the PR labels, files modified, etc.

In my experience, 'keep a changelog' is pure pain

**Comment by loosebazooka** [comment]
I'm okay changing this in the future, I'm going to merge it in for now.

**Pull request merged**
