### PR TITLE
Fix timeout and add backoff for http requests

### PR DESCRIPTION
**Pull request by loosebazooka**
Signed-off-by: Appu Goundan <appu@google.com>

I believe this fixes the issues our CI is running into with no timeouts, and no good backoff policy.

### CODE REVIEW

**Review by vlsi — APPROVED** [review]

**Comment by loosebazooka** [comment]
It feels like there might just be a bug in the jdk that is being used here.

**Comment by vlsi** [comment]
Here's a stacktrace of a hanging thread:

```
"WorkerExecutor Queue" #466 prio=5 os_prio=0 cpu=895.70ms elapsed=3.39s tid=0x00007fa4d0359000 nid=0x200c runnable  [0x00007fa4c709e000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.17/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.17/SocketInputStream.java:115)
	at java.net.SocketInputStream.read(java.base@11.0.17/SocketInputStream.java:168)
	at java.net.SocketInputStream.read(java.base@11.0.17/SocketInputStream.java:140)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@11.0.17/SSLSocketInputRecord.java:478)
	at sun.security.ssl.SSLSocketInputRecord.readHeader(java.base@11.0.17/SSLSocketInputRecord.java:472)
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(java.base@11.0.17/SSLSocketInputRecord.java:70)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(java.base@11.0.17/SSLSocketImpl.java:1454)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(java.base@11.0.17/SSLSocketImpl.java:1065)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.google.api.client.http.apache.v2.ApacheHttpRequest.execute(ApacheHttpRequest.java:73)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
	at dev.sigstore.rekor.client.RekorClient.putEntry(RekorClient.java:89)
	at dev.sigstore.KeylessSigner.sign(KeylessSigner.java:189)
	at dev.sigstore.KeylessSigner.signFiles(KeylessSigner.java:234)
	at dev.sigstore.KeylessSigner.signFile(KeylessSigner.java:252)
	at dev.sigstore.sign.work.SignWorkAction.execute(SignWorkAction.kt:55)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
```

I guess the timeouts are not propagating properly to the HTTP client.
In other words, the default timeouts are set to `60 seconds` (connect timeout, read timeout), and it does not play well with test timeout of 60 seconds.

I guess we might want to reduce connect/read timeouts and/or configure Rekor in such a way that it immediately rejects connections instead of being silent on the wire.

**Comment by vlsi** [comment]
Here's a better dump: https://github.com/sigstore/sigstore-java/actions/runs/3893536250/jobs/6646270545

```
2023-01-11T14:13:45.1180316Z "WorkerExecutor Queue Thread 2" #465 prio=5 os_prio=0 cpu=819.17ms elapsed=41.58s tid=0x0000561436e29000 nid=0x1f1e waiting on condition  [0x00007f43f47fc000]
2023-01-11T14:13:45.1180563Z    java.lang.Thread.State: WAITING (parking)
2023-01-11T14:13:45.1180857Z    at jdk.internal.misc.Unsafe.park(java.base@11.0.17/Native Method)
2023-01-11T14:13:45.1181316Z    - parking to wait for  <0x000000009f7b8288> (a io.grpc.stub.ClientCalls$ThreadlessExecutor)
2023-01-11T14:13:45.1181694Z    at java.util.concurrent.locks.LockSupport.park(java.base@11.0.17/LockSupport.java:194)
2023-01-11T14:13:45.1182387Z    at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:748)
2023-01-11T14:13:45.1182706Z    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:157)
2023-01-11T14:13:45.1183102Z    at dev.sigstore.fulcio.v2.CAGrpc$CABlockingStub.createSigningCertificate(CAGrpc.java:230)
2023-01-11T14:13:45.1183493Z    at dev.sigstore.fulcio.client.FulcioClient.signingCertificate(FulcioClient.java:125)
2023-01-11T14:13:45.1183929Z    at dev.sigstore.KeylessSigner.sign(KeylessSigner.java:170)
2023-01-11T14:13:45.1184385Z    at dev.sigstore.KeylessSigner.signFiles(KeylessSigner.java:234)
2023-01-11T14:13:45.1185088Z    at dev.sigstore.KeylessSigner.signFile(KeylessSigner.java:252)
2023-01-11T14:13:45.1185558Z    at dev.sigstore.sign.work.SignWorkAction.execute(SignWorkAction.kt:55)
2023-01-11T14:13:45.1185965Z    at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
2023-01-11T14:13:45.1186429Z    at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
2023-01-11T14:13:45.1186862Z    at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
2023-01-11T14:13:45.1187350Z    at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
2023-01-11T14:13:45.1187885Z    at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
2023-01-11T14:13:45.1188325Z    at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
2023-01-11T14:13:45.1188934Z    at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
2023-01-11T14:13:45.1189613Z    at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1.lambda$execute$0(IsolatedClassloaderWorkerFactory.java:57)
2023-01-11T14:13:45.1190254Z    at org.gradle.workers.internal.IsolatedClassloaderWorkerFactory$1$$Lambda$1169/0x0000000100a57c40.execute(Unknown Source)
2023-01-11T14:13:45.1190773Z    at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
2023-01-11T14:13:45.1191134Z    at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
2023-01-11T14:13:45.1191705Z    at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
2023-01-11T14:13:45.1192294Z    at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
2023-01-11T14:13:45.1192769Z    at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
2023-01-11T14:13:45.1193258Z    at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)

...

2023-01-11T14:13:45.1205295Z "WorkerExecutor Queue Thread 3" #466 prio=5 os_prio=0 cpu=2084.81ms elapsed=41.57s tid=0x0000561436e2a800 nid=0x1f1f waiting on condition  [0x00007f43f1bfa000]
2023-01-11T14:13:45.1205527Z    java.lang.Thread.State: WAITING (parking)
2023-01-11T14:13:45.1205802Z    at jdk.internal.misc.Unsafe.park(java.base@11.0.17/Native Method)
2023-01-11T14:13:45.1206239Z    - parking to wait for  <0x000000009f7b84d8> (a io.grpc.stub.ClientCalls$ThreadlessExecutor)
2023-01-11T14:13:45.1206591Z    at java.util.concurrent.locks.LockSupport.park(java.base@11.0.17/LockSupport.java:194)
2023-01-11T14:13:45.1206910Z    at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:748)
2023-01-11T14:13:45.1207208Z    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:157)
2023-01-11T14:13:45.1207580Z    at dev.sigstore.fulcio.v2.CAGrpc$CABlockingStub.createSigningCertificate(CAGrpc.java:230)
2023-01-11T14:13:45.1208129Z    at dev.sigstore.fulcio.client.FulcioClient.signingCertificate(FulcioClient.java:125)
2023-01-11T14:13:45.1208792Z    at dev.sigstore.KeylessSigner.sign(KeylessSigner.java:170)
2023-01-11T14:13:45.1209164Z    at dev.sigstore.KeylessSigner.signFiles(KeylessSigner.java:234)
2023-01-11T14:13:45.1209461Z    at dev.sigstore.KeylessSigner.signFile(KeylessSigner.java:252)
2023-01-11T14:13:45.1209778Z    at dev.sigstore.sign.work.SignWorkAction.execute(SignWorkAction.kt:55)
2023-01-11T14:13:45.1210183Z    at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
2023-01-11T14:13:45.1210603Z    at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
2023-01-11T14:13:45.1211020Z    at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
2023-01-11T14:13:45.1211496Z    at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
...

2023-01-11T14:14:02.9189146Z ##[group]dev.sigstore.gradle.SigstorePublishSignTest > sign file(TestedGradle, TestedSigstoreJava)[9], [9] gradle=TestedGradle(version=7.5.1, configurationCache=OFF), sigstoreJava=Versi
2023-01-11T14:14:02.9272338Z ##[error] 60.0sec dev.sigstore.gradle.SigstorePublishSignTest > sign file(TestedGradle, TestedSigstoreJava)[9], [9] gradle=TestedGradle(version=7.5.1, configurationCache=OFF), sigstoreJ
java.util.concurrent.TimeoutException: sign file(dev.sigstore.testkit.TestedGradle, dev.sigstore.testkit.TestedSigstoreJava) timed out after 60 seconds
```

Looks like a fulcio timeout to me

**Comment by loosebazooka** [comment]
Interesting,  okay I added a timeout to the fuclio call, but there's some unusual interaction going on, since the piece that installs the sigstore dependency is also blocked?

**Comment by vlsi** [comment]
I've added `--info` to a top-level Gradle, and it shows we have `OutOfMemory: metaspace`

https://github.com/sigstore/sigstore-java/actions/runs/3895325792/jobs/6650500623#step:6:22052

```
    Runnable threw exception
    java.lang.OutOfMemoryError: Metaspace
    	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
    	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
    	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
    	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
    	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
    	at java.base/java.security.AccessController.doPrivileged(Native Method)
    	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
    	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
    	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    	at io.grpc.internal.ManagedChannelImpl$ChannelStreamProvider.newStream(ManagedChannelImpl.java:600)
    	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:258)
    	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:191)
    	at io.grpc.internal.DelayedClientCall$2.run(DelayedClientCall.java:188)
    	at io.grpc.internal.DelayedClientCall.drainPendingCalls(DelayedClientCall.java:286)
    	at io.grpc.internal.DelayedClientCall.access$100(DelayedClientCall.java:50)
    	at io.grpc.internal.DelayedClientCall$1.runInContext(DelayedClientCall.java:158)
    	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    	at io.grpc.internal.ManagedChannelImpl$RealChannel$PendingCall$1.run(ManagedChannelImpl.java:1113)
    	at io.grpc.stub.ClientCalls$ThreadlessExecutor.runQuietly(ClientCalls.java:773)
    	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:756)
    	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:157)
    	at dev.sigstore.fulcio.v2.CAGrpc$CABlockingStub.createSigningCertificate(CAGrpc.java:230)
    	at dev.sigstore.fulcio.client.FulcioClient.signingCertificate(FulcioClient.java:125)
    	at dev.sigstore.KeylessSigner.sign(KeylessSigner.java:170)
    	at dev.sigstore.KeylessSigner.signFiles(KeylessSigner.java:234)
    	at dev.sigstore.KeylessSigner.signFile(KeylessSigner.java:252)
    	at dev.sigstore.sign.work.SignWorkAction.execute(SignWorkAction.kt:55)
    	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
    	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
    	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
    	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
    [Channel<1>: (fulcio.sigstore.dev)] Uncaught exception in the SynchronizationContext. Panic!
    java.lang.OutOfMemoryError: Metaspace
    [Channel<1>: (fulcio.sigstore.dev)] Uncaught exception in the SynchronizationContext. Panic!
    java.lang.OutOfMemoryError: Metaspace
    Expiring Daemon due to JVM Metaspace space being exhausted
    Daemon will be stopped at the end of the build after running out of JVM memory
    Exception in thread "grpc-default-executor-0" java.lang.OutOfMemoryError: Metaspace
    An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
    io.grpc.netty.shaded.io.netty.channel.ChannelPipelineException: io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.handlerAdded() has thrown an exception; removed.
    	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:624)
    	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
    	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
    	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
    	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
    	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
    	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
    	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
    	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:394)
    	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    	at java.base@11.0.17/java.lang.Thread.run(Thread.java:829)
```

**Comment by vlsi** [comment]
The failure is noticeable in local execution:

```
$ CI=Y ./gradlew :sigstore-gradle:sigstore-gradle-sign-plugin:test --tests dev.sigstore.gradle.SigstorePublishSignTest
```

I've captured a heap dump, and found one of the reasons classloaders were not released:

```
BC Entropy Daemon
Thread 0x414d27db0
  at java.lang.Thread.sleep(J)V (Native Method)
  at org.bouncycastle.jcajce.provider.drbg.DRBG$EntropyDaemon.run()V (Unknown Source)
  at java.lang.Thread.run()V (Thread.java:829)
```

I guess https://github.com/bcgit/bc-java/issues/1254 is relevant.

So the ways out are:
a) move to process isolation
b) wait until bouncycastle adds API to terminate the thread and/or makes the thread optional

**Comment by loosebazooka** [comment]
Good catch, I think the changes in here are still relevant as we weren't timing out properly before.

**Review by vlsi — APPROVED** [review]

**Pull request merged**
