### PR TITLE
Fail if we can't parse a key and bc isn't present

### PR DESCRIPTION
**Pull request by loosebazooka**
Signed-off-by: Appu Goundan <appu@google.com>

Auto-adding bc scared me a bit, wdyt about this?

### CODE REVIEW

**Comment by loosebazooka** [comment]
I don't have a great answer here. But I err on the side of caution?

**Comment by patflynn** [comment]
Before we merge this I'd like to see some general recommendation that we shouldn't do it.  I couldn't find anything online, but maybe you can check with the java illuminati at Google?

**Comment by loosebazooka** [comment]
oh this PR is mostly a question, so yeah lemme change it to a draft

**Comment by loosebazooka** [comment]
or alternatively can we just pull it in if we encounter an eddsa key?

**Pull request closed without merging**
